### ISSUE TITLE
connect() improperly hides some errors

### ISSUE THREAD

**Issue by bmhkim** [fabric/fabric#1263] opened 2015-01-30 17:31 UTC
Fabric seems to be incorrectly hiding the cause of an exception in network.py:538's sys.exit(0) call.

I had a weird environment (please don't ask why, just accept that it's the source of the exception that was being hidden) where I was using an old version of paramiko. The client in paramiko didn't have the sock kwarg, so Python was raising a TypeError. Unfortunately, the error handler for ctrl-d/ctrl-c seems to fail to validate that the exception caught is actually the one the developer is expecting. As a result, other errors are silently being ignored.

Ubuntu 14.04 amd64
Python 2.7.6
Fabric 1.10.1
Paramiko 1.7.7 (An old version, and the source of my crash, but *NOT* the bug per se)

I acknowledge this is a weird case that should not ever happen. Nevertheless, it was a minor pain figuring out what was going on, so I'm submitting it for review.

**Comment by bitprophet** [comment] 2015-02-04 00:24
Wow. So, I spelunked and the TypeError was added 8 years ago, prior even to my involvement: ba6ad56b41f368627b34eb384f6cdac453db9ac9

That explains why I don't remember the specifics about why Ctrl-C raises TypeError...

Can you provide the details about the TypeError you got so I can more easily compare it with whatever Ctrl-C is spitting out? I'm poking at what the "expected" TypeError is now (it's amusingly hard to futz with because catching / not catching these exceptions leads to random end-of-process fails. Oh threading.)

**Comment by bitprophet** [comment] 2015-02-04 00:36
Interestingly at this point in time I can't actually get that block to trigger when Ctrl-C/Ctrl-D'ing at a prompt, it takes an entirely different code path. And due to its age it's really unclear what the original rationale is (but also makes me afraid to, for example, just rip it out and see if nothing breaks.)

Interested to hear the details from your issue, for sure, at this point.

**Comment by bmhkim** [comment] 2015-02-04 06:17
The issue I ran into is that my old version of paramiko doesn't have the 'sock' argument to client.connect. As a result, paramiko.client(....sock=sock) fails with a TypeError that client got an unexpected keyword argument 'sock'.

**Comment by bitprophet** [comment] 2015-02-06 22:18
Gotcha. Sadly given what I posted above, I don't think it's worth the risk of tweaking that line to handle this sort of (admittedly, as you said) oddball corner case. It sucks that it obscured the root cause :(

Hopefully having this on record will help some folks Googling in the future, at least. Thanks for the report! Closing as 'wontfix' for the time being.

**Closed by bitprophet** 2015-02-06 22:18 UTC
Labels: Bug, Needs investigation, Network

**Comment by bitprophet** [comment] 2015-02-07 00:52
In a hilarious twist of fate I just got another "paramiko yielded a TypeError" - just like the one described here - on my end when troubleshooting an entirely unrelated problem (in Paramiko, using Fabric to test).

I'm not sure what that says about the universe except that it doesn't like me or my approach to life :(

**Comment by bmhkim** [comment] 2015-02-09 19:03
Yeah...I can't say I'm exactly thrilled with the decision to close the issue, although I understand your rationale not wanting to break things. On the other hand, that sort of philosophy tends to cause dead code bloat, which I also hate.

I propose a way to try to gather a bit of data. Would you be open to figuring out a way to instrument a future (beta?) build in a way that would help to identify if this case is being reached in normal operation, and what the parameters of those exceptions are?

**Comment by bitprophet** [comment] 2015-02-12 00:33
I looked and did find one other ticket, #849. Two tickets in the span of 8 years still sounds like fuel for "it's not actually very common".

Yes, it'd be ideal to figure out how often it is "really" happening (or the inverse, to somehow A/B test the change to see whether the TypeError catch is still performing useful behavior) but there's no good way to accomplish that with this sort of library that I'm aware of. Certainly not one that wouldn't add a disproportionate amount of extra effort :(

I am on the road to writing a 2.0 rewrite of Fabric, during which all of these old bits of code are getting a 2nd look, so my preference for now is still to be conservative in this version of the code, and chances are 2.0 won't include it unless I can reproduce whatever it was intended for.

----

All that said, if you can find more evidence of this biting people (eg...StackOverflow or mailing list posts) or if more folks report it in the future, that would be grounds to revisit.

**Comment by bmhkim** [comment] 2015-02-12 18:17
I would agree that this seems to be a rare error. Given that you're doing a rewrite, I'll stop pestering you. :)

Thanks for your hard work on fabric!
