### ISSUE TITLE
WinError87 when executing local on Connection

### ISSUE THREAD

**Issue by KantiCodes** [fabric/fabric#2142] opened 2021-02-19 13:13 UTC
Hi all, I`m new to Invoke and even newer to Fabric!

I have some functionality in Invoke and now I`m trying to make a similar demo using **fabric**

Following code results in WinError87
![image](https://user-images.githubusercontent.com/24612001/108508418-14019c00-72bc-11eb-8dc5-055ab9f94fd3.png)

![image](https://user-images.githubusercontent.com/24612001/108508478-2bd92000-72bc-11eb-8abf-192437f95790.png)
[WinError 87] Parameter is incorrect

I know it's probably caused by me misunderstanding something - but I`d really appreciate a hint :)

Setup:

Python 3.8.5
Fabric 2.6.0

**Comment by davidjmemmett** [comment] 2021-02-19 13:45
Hi KantiCodes,

Just to confirm, you have an SSH server running on localhost on port 8050, and the username you're wanting to connect to is 45502?

Which SSH server are you using? If you open an SSH connection using the standard openssh client (`ssh 45502@localhost -p8050`) and run `cd ..`, does this work as expected?

Cheers,
David

**Comment by KantiCodes** [comment] 2021-02-19 13:56
Hi @davidjmemmett 

Thanks so much for taking time to look at my problem :)

No, I do not have an SSH running - my understanding was that until I only run c.local() the connection is not established and it's just as if I was using invoke.

Sorry about that.

To add a little background to what I want to do.

I created invoke module and wrapped it into my own pip installing library: http://docs.pyinvoke.org/en/stable/concepts/library.html#reusing-invoke-s-cli-module-as-a-distinct-binary

Here is a simplified example:

tasker/main.py
![image](https://user-images.githubusercontent.com/24612001/108511244-f0d8eb80-72bf-11eb-9615-17616d5a194d.png)

tasker/tasks.py
![image](https://user-images.githubusercontent.com/24612001/108511278-fc2c1700-72bf-11eb-99ea-42ec78696e45.png)

I can install and access my wrapped "module"

![image](https://user-images.githubusercontent.com/24612001/108511451-385f7780-72c0-11eb-89b9-1369ac86c827.png)

Now my goal:
- For some of the tasks I need to communicate with web server, therefore I would like to use Fabric and keep my current(Invoke's) functionality and add new tasks that.

As far as I understand @bitprophet designed fabric to be **Invoke +** therefore I would like to keep my Invoke solution and add being able to connect over SSH to web servers.

To wrap up:
I want to create a fabric module performing tasks both locally and externally(over ssh) and wrap that into a pip package that I can install :D...

I am all new to this topic - let me know if my intentions are clear

**Comment by davidjmemmett** [comment] 2021-02-19 13:59
Gotcha - would you be able to provide the full stack trace please? I'd like to see what's happening further up the stack.

**Comment by KantiCodes** [comment] 2021-02-19 14:08
Hey. there you go.
![image](https://user-images.githubusercontent.com/24612001/108514507-3eefee00-72c4-11eb-8711-3d20aaed26ba.png)

**Comment by davidjmemmett** [comment] 2021-02-20 20:08
From what I can see, this _appears_ to be an invoke issue - cc'ing @jefftriplett

I don't have a Microsoft Windows machine at hand to test this with I'm afraid.

**Comment by jefftriplett** [comment] 2021-02-20 21:03
Sadly, I don't have a Windows machine to test either. 

I'm a little confused by using `local` through with a remote connection though. I do see it's documented in the docs by what looks like a pass-through to invoke. 

I would try using `invoke.run()` locally to see if you get the same error. The locals sort-of lead me to this from https://docs.fabfile.org/en/2.5/api/connection.html#fabric.connection.Connection.local to http://docs.pyinvoke.org/en/latest/api/__init__.html#invoke.run

**Comment by KantiCodes** [comment] 2021-02-21 13:20
Thanks for your answer @jefftriplett.

The reason why I would like to use **fabric.local** instead of the **invoke.run** is following:

- As I described my end goal above the tool I`m building is going to use both Invoke and Fabric and it is my understanding that I need to build a Fabric tool that uses invoke (either by sub classing or explicitly) and not the other way around.

Nonetheless I have seen some code examples where people were doing following:
root/tasks.py
![image](https://user-images.githubusercontent.com/24612001/108626230-69ba7d80-744f-11eb-8008-a78e7f3c7945.png)
- **Note that the task is from invoke**

root/main.py
![image](https://user-images.githubusercontent.com/24612001/108626208-53142680-744f-11eb-8ed4-95f759fee72b.png)

So now I am a little bit confused which one to choose. I do understand though that using **fabric.local()** is equivalent to **invoke.run()** I just thought that's the way to go.

**Comment by jefftriplett** [comment] 2021-02-21 15:41
@KantiCodes sorry for the confusion. I was mostly curious if one worked vs. the other to help us figure out if the issue was really Invoke or Fabric since neither of us has a Windows machine to test it on.

**Comment by KantiCodes** [comment] 2021-02-21 17:52
No probs.

To answer your question: Invoke works properly.

**Comment by KantiCodes** [comment] 2021-02-21 17:59
Btw, could you elaborate on the screen shoot I sent?

What do u think about using Fabric functionality inside  invoke`@task`?

**Comment by davidjmemmett** [comment] 2021-02-22 20:47
I'm convinced that the issue you're having is related to the Microsoft Windows executor, rather than anything odd happening between invoke and fabric _invoking_ invoke. I'll spin up a Microsoft Windows test VM and have a play. For now, here's my findings:

**tasks.py**:
```python

from invoke import task
from fabric import Connection

@task
def test(c):
    c.run('echo test from invoke')

    fab_c = Connection('localhost')
    fab_c.local('echo test from invoke via fabric')
```

**fabfile.py is a symbolic link to tasks.py, meaning they're identical**:
```
$ stat fabfile.py 
  File: fabfile.py -> tasks.py
  Size: 8         	Blocks: 0          IO Block: 4096   symbolic link
Device: 802h/2050d	Inode: 1192219     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/   david)   Gid: ( 1000/   david)
Access: 2021-02-22 20:41:32.409633886 +0000
Modify: 2021-02-22 20:41:30.489574349 +0000
Change: 2021-02-22 20:41:30.489574349 +0000
 Birth: -
```

**invoke output**:
```
$ inv test
test from invoke
test from invoke via fabric
```
**fabric output**:
```
$ fab test
test from invoke
test from invoke via fabric
```

**Comment by davidjmemmett** [comment] 2021-02-22 21:52
Hi @KantiCodes,

I'm afraid I'm unable to reproduce this.

The steps I took:

1. Create a Microsoft Windows 10 VM using the [free images provided](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).
2. Installed [Python 3.6.6](https://www.python.org/downloads/release/python-366/) using the `Windows x86-64 executable installer` (checked the box to add `python` to the $PATH.
3. Launched Microsoft PowerShell
4. Upgraded `pip`:
    `> python -m pip install --upgrade pip`
5. Installed `fabric`
    `> python -m pip install fabric`
6. Created a `tasks.py` identical to the one above:
    `> notepad.exe tasks.py`
7. Copied `tasks.py` into `fabfile.py` (as Microsoft Windows still doesn't properly support symbolic links apparently):
    `> cp tasks.py fabfile.py`

```
PS C:\Users\IEUser> inv test
test from invoke
test from fabric
PS C:\Users\IEUser> fab test
test from invoke
test from fabric
```

Even after replacing the `echo` calls with `cd ..`, it had no effect.

Can you please provide a small, standalone `fabfile.py` to reproduce this issue please? If possible, using a clean VM environment to test this would be preferable.

Cheers,
David

**Comment by davidjmemmett** [comment] 2021-02-22 21:55
I do apologise, you're using Python 3.8.5; I'll grab that and test!

**Comment by davidjmemmett** [comment] 2021-02-22 22:04
Aha, this is definitely related to the Python version. I've managed to reproduce this issue using Python 3.8.5.

**Comment by davidjmemmett** [comment] 2021-02-22 22:14
I've also managed to reproduce this issue using Python 3.8.8 (latest 3.8).

**Comment by davidjmemmett** [comment] 2021-02-22 22:26
Even in the latest Python 3.9.2 released a couple of days ago.

**Comment by davidjmemmett** [comment] 2021-02-22 22:29
I've narrowed the issue itself down to `env` being dropped when running under `fabric`. Dumping the arguments to `invoke.runners.Local:start` shows that `env` is fully populated when running under invoke, but an empty dictionary when running under `fabric`.

**Comment by davidjmemmett** [comment] 2021-02-22 23:01
It looks like this is [a known issue](https://github.com/fabric/fabric/commit/4358f344e5d6b59dc99d954ad8287b4021d0ed81). If I set `replace_env` to `False`, it works as expected, however this will need to be set specifically for local calls only and never for remove calls. I wonder why it worked with Python 3.6.6 though... weird.

I'll continue to investigate.

**Comment by davidjmemmett** [comment] 2021-02-23 00:40
Hi @KantiCodes,

As a temporary test (**please do not rely on this long-term**), you _could_ install fabric from the commit I pushed to see if this fixes the issue for you:

```bash
python -m pip install git+https://github.com/davidjmemmett/fabric.git@f8cf9ad30efb773f055bf7c174ef98ba225405fc
```

Cheers,
David

**Comment by davidjmemmett** [comment] 2021-02-23 00:42
Disclaimer: given the nature of this commit, there are potential security implications (whereby local environment variables have the potential to be transmitted unknowingly): i.e. it's not yet been reviewed.

**Comment by KantiCodes** [comment] 2021-02-24 08:49
Hi @davidjmemmett,

Considering what you wrote, for now I will just stick with Invoke instead of sub-classing.

**Comment by bitprophet** [comment] 2021-03-05 16:36
Thanks for triaging this David! I may be reading too fast but I don't see if we've found what changed in Python 3.8 to break this - the ultimate change you identified needs to happen regardless, but it's weird if Python 3.6 and 3.7 don't trigger the issue.

@KantiCodes as David and Jeff noted, using "straight Invoke" is fine here, especially if it works around the issue for now. Eventually I do want "just use Fabric because you intend to do both local and remote things" to be a smooth experience - it's not there yet unfortunately. Mixing the two in the same code shouldn't be all that much more annoying for now, hopefully!

I'm talking with David in his PR and I expect to merge it sometime, so let's close this to roll it into there. Thanks for the report!

**Closed by bitprophet** 2021-03-05 16:36 UTC
Labels: Awaiting feedback, Nonstandard platforms, Python versions

**Comment by fripSide** [comment] 2021-05-14 08:16
I also meet the same problem. In Python 3.8.5 with Fabric 2.6.9, I failed to execute local commend in CMD with either ctx.run or conn.local.
`
from fabric import task, Connection

@task
def test(ctx):
    conn = Connection("xxx")
    ctx.run("cd D:/")
    # conn.local("cd D:/")
`

The error message is,
  File "d:\dev\python\python3.8.5\lib\site-packages\invoke\runners.py", line 1271, in start
    self.process = Popen(
  File "d:\dev\python\python3.8.5\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "d:\dev\python\python3.8.5\lib\subprocess.py", line 1308, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87]

**Comment by wookiesh** [comment] 2021-08-24 18:45
Hello, I'm experiencing the same issue here with pythonpython 3.9.6 and fabric 2.6 (up to date according to poetry ?) but the issue is closed.

Any pointer on how to address it ?

**Comment by davidjmemmett** [comment] 2021-08-24 19:28
There hasn't been a release for a while - @bitprophet
