### ISSUE TITLE
`Connection_.init.forward_agent.defaults_to_False` fails when ssh-config enables agent forwarding for `*`

### ISSUE THREAD

**Issue by offbyone** [fabric/fabric#1753] opened 2018-05-14 15:19 UTC
For example, ssh-config contains this:

```
Host *
    ForwardAgent=yes
```

This manifests as follows:

```
================================================================================================================= FAILURES ==================================================================================================================
_____________________________________________________________________________________________ Connection_.init.forward_agent.defaults_to_False ______________________________________________________________________________________________

self = <connection.Connection_.init.forward_agent object at 0x10c59c048>

    def defaults_to_False(self):
>       assert Connection('host').forward_agent is False
E       AssertionError: assert True is False
E        +  where True = <Connection host=host>.forward_agent
E        +    where <Connection host=host> = Connection('host')

tests/connection.py:161: AssertionError
============================================================================================== 1 failed, 229 passed, 6 skipped in 2.63 seconds ==============================================================================================
```

**Comment by offbyone** [comment] 2018-05-14 15:36
This specifically references code in https://github.com/fabric/fabric/blob/master/fabric/connection.py#L309-L311

That bit there pulls in global SSH config, which isn't always `False` for `Host: *`.

**Comment by offbyone** [comment] 2018-05-16 16:12
Okay, so... once paramiko/paramiko#1209 and paramiko/paramiko#1212 are merged in this can go forward :)

**Comment by bitprophet** [comment] 2018-06-14 23:41
Those issues are now closed, leaving me trying to remember exactly what we need to do here:

- IIRC the proximate problem was that Chris was simply unable to run our tests, period, because his test environment has an SSH config that violates the test...
  - So a proximate solution would be e.g. to update the test/suite so it forces SSH config loading off by default
  - I don't see another, deeper solution offhand given the rest of the system is operating as intended (SSH config loading enabled by default, purposefully; and `Connection.forward_agent` reflecting the union of regular config and SSH config, with latter winnin)
- An orthogonal problem was a few lines of ugly code at the Fabric level that is now fixed by the new Paramiko feature added in paramiko/paramiko#1212
  - Though if we want to rely on that, we need to bump up the required Paramiko version to 2.5. Ugh!
  - Probably just wants to be a "for Fabric 3.0" TODO instead. I need to settle on a better way to manage that anyways, even if it's just literally `# TODO 3.0: xxx`

**Comment by bitprophet** [comment] 2018-06-14 23:49
I note that almost all other SSH config related connection/config params in `tests/connection.py` already state `load_ssh_configs=False` in their overrides. So this is almost just an oversight in that regard.

We test the default behavior of SSH config loading (i.e. the fact that it is on by default) over in `tests/config.py`, so I suspect a global "no ssh config loading please" in `tests/connection.py` would be appropriate. Will see how much of a refactoring pain that is.

**Comment by bitprophet** [comment] 2018-06-15 00:42
Nice, in setting that up I found a real shite bug, namely that gatewaying does not persist the outer connection's config object. So eg if you turn off SSH config loading but specify a jump host, the inner connection for the jump host...will load SSH config...!

(And in my case, I had a 'Host *' ProxyJump with no other PRoxyJump set up, meaning infinite recursion! TOOT TOOT)

**Comment by bitprophet** [comment] 2018-06-15 00:53
I think this is Fixed Enough™ and now future edits to the connection test module will default to not loading SSH conf files at all. Not beautiful, but whatever.

**Closed** 2018-06-15 00:54 UTC
