### ISSUE TITLE
fabric env.hosts not being identified

### ISSUE THREAD

**Issue by c0n71nu3** [fabric/fabric#1577] opened 2017-03-22 15:56 UTC
Need help with the below:
I have a simple fabfile by the name 
**env_fabfile.py**

    # env_fabfile.py
    # makes use of fab env variables 
    
    from fabric.api import env, run
    def login():
        env.hosts = ['user@host1:1234', 'user@host2:2345']
        env.passwords = {'user@host1:1234': 'pass1', 'user@host2:2345': 'pass2'}
        env.parallel=True
    
    def run_lsb_release():
        run('lsb_release -a')

Now I run the above using the fab command as :
> fab -f env_fabfile.py login run_lsb_release

And it runs perfectly (in parallel) and gives the desired output

Now I wanted to actually calculate the time difference between when the same script is run in serial vs when it is run in parallel. So to do this I wrote the below python script:
**timecal.py**

    # timecal.py
    # runs the fabfile once in serial and calculates the time
    # then runs the same file in parallel and calculates the time
    
    from fabric.api import env, run
    import time
    
    def login():
        print "in login"
        env.hosts = ['user@host1:1234', 'user@host2:2345']
        env.passwords = {'user@host1:1234': 'pass1', 'user@host2:2345': 'pass2'}
    
    def parallel(status):
        print "in parallel"
        env.parallel=status
        
    def run_lsb_release():
        print "in run"
        run('lsb_release -a')
    
    def do_serial():
        start_time = time.time()
        parallel(False)
        login()
        run_lsb_release()
        elapsed_time = time.time() - start_time
        return elapsed_time
    
    def do_parallel():
        start_time = time.time()
        parallel(True)
        login()
        run_lsb_release()
        elapsed_time = time.time() - start_time
        return elapsed_time
    
    
    if __name__ == '__main__':  
        print "Running in serial mode "
        print "Total time taken ", do_serial()
    
        print "Running in parallel mode"
        print "Total time taken ", do_parallel()

but when I run timecal.py as 
> python timecal.py

I get the below on stdout (apart from the print statements in the code)
> No hosts found. Please specify (single) host string for connection:

I don't understand why ? Also how can the script be rectified so that I can achieve what I want to (as stated in the question above)

In case I try a different version of timecal.py, as :

    from fabric.api import run, settings, env
    import time
    
    def do_parallel():
        start_time = time.time()
        env.hosts = ['user@host1:1234', 'user@host2:2345']
        env.passwords = {'user@host1:1234': 'pass1', 'user@host2:2345': 'pass2'}
        env.parallel=True
        run('lsb_release -a')
        elapsed_time = time.time() - start_time
        return elapsed_time
    
    def do_serial():
        start_time = time.time()
        with settings(host_string='host1', port=1234, user='user', password='pass1'):
            run('lsb_release -a')
        with settings(host_string='host2', port=2345, user='user', password='pass2'):
            run('lsb_release -a')
        elapsed_time = time.time() - start_time
        return elapsed_time
    
    if __name__ == '__main__':  
        try:
            print "Running in parallel mode"
            print "Total time taken ", do_parallel()
    
            print "Running in serial mode "
            print "Total time taken ", do_serial()
        except Exception as e:
            print e

I get the below error :
> Fatal error: Needed to prompt for the target host connection string (host: None), but input would be ambiguous in parallel mode

I don't understand why is the host: None here ? What is wrong with the code ?

**Comment by bitprophet** [comment] 2017-03-22 18:48
At a glance I think it's because you're setting `env.hosts` but then expecting `run` to honor that directly; it doesn't actually, it only honors `env.host_string`; `env.hosts` is used by the higher level task-execution machinery. See e.g. http://docs.fabfile.org/en/1.13/usage/execution.html#connections and the rest of that document :)

Closing as "probably not a bug" but comments can continue. Thanks!

**Closed by bitprophet** 2017-03-22 18:48 UTC

**Comment by ploxiln** [comment] 2017-03-22 19:47
Executing fabric tasks as fabric tasks is not as simple as calling the python function. When you list the task on the command-line it does more than that. You would probably be interested in the `execute()` function: http://docs.fabfile.org/en/1.13/usage/execution.html#intelligently-executing-tasks-with-execute

**Comment by c0n71nu3** [comment] 2017-03-23 07:20
Yeah.. I kinda figured that out. Thanks anyway for the advice. execute seems to do the job. However, in case of the do_serial() in the below code, even run seems to work fine. It's only with respect to parallel execution that execute seems to be absolutely required :

```from fabric.api import run, settings, env
import time
from fabric.tasks import execute

def do_parallel():
    try:
        start_time = time.time()
        env.hosts = ['user@host1:1234', 'user@host2:2345']
        env.passwords = {'user@host1:1234': 'pass1', 'user@host2:2345': 'pass2'}
        env.parallel=True
        # the line below will give errors. TO rectify it, comment it out and uncomment the execute line
        execute(run_lsb_release)
        elapsed_time = time.time() - start_time
        return elapsed_time
    except Exception as e:
        print e


def run_lsb_release():
    run('lsb_release -a')


def do_serial():
    try: 
        start_time = time.time()
        with settings(host_string='host1', port=1234, user='user', password='pass1'):
            run('lsb_release -a')
        with settings(host_string='host2', port=2345, user='user', password='pass2'):
            run('lsb_release -a')
        elapsed_time = time.time() - start_time
        return elapsed_time
    except Exception as e:
        print e


if __name__ == '__main__':  
    print "Running in serial mode "
    total_time = do_serial()
    print "Total time taken ", total_time
    print "\n\n"
    print "Running in parallel mode"
    total_time = do_parallel()
    print "Total time taken ", total_time```

**Comment by c0n71nu3** [comment] 2017-03-23 07:25
But now if I try to do the same thing above using the *@parallel* decorator instead, things seem to be getting messed up again, and I once again don't understand why. Looking forward to some advice again. 

```from fabric.api import run, settings, env, parallel, task, hosts, serial
import time
from fabric.tasks import execute


my_hosts = ('user@host1:1234', 'user@host2:2345')
@hosts(my_hosts)
@task(name='run quickly')
@parallel
def do_parallel():
    try:
        start_time = time.time()
        env.passwords = {'user@host1:1234': 'pass1', 'user@host2:2345': 'pass2'}
        execute(run_lsb_release)
        elapsed_time = time.time() - start_time
        return elapsed_time
    except Exception as e:
        print e


def run_lsb_release():
    run('lsb_release -a')

@task
@serial
def do_serial():
    try: 
        start_time = time.time()
        with settings(host_string='host1', port=1234, user='user', password='pass1'):
            run('lsb_release -a')
        with settings(host_string='host2', port=2345, user='user', password='pass2'):
            run('lsb_release -a')
            run('lsb_release -a')
        elapsed_time = time.time() - start_time
        return elapsed_time
    except Exception as e:
        print e
    

if __name__ == '__main__':  
    print "Running in parallel mode"
    total_time = do_parallel()
    print "Total time taken ", total_time
    
    print "\n\n"

    print "Running in serial mode "
    total_time = do_serial()
    print "Total time taken ", total_time```

And the output I get is
> No hosts found. Please specify (single) host string for connection

prompting for host. Don't know why it is not reading the host at all?
