### ISSUE TITLE
IOError: [Errno 11] Resource temporarily unavailable in parallel mode

### ISSUE THREAD

**Issue by dreame4** [fabric/fabric#1402] opened 2015-11-20 20:05 UTC
When I run fab in parallel mode (`-P 16`) and collect a lot of output, always one or more of my tasks fail with the following error:

```
Traceback (most recent call last):
  File /home/me/.virtualenvs/proj/local/lib/python2.7/site-packages/fabric/main.py, line 743, in main
    *args, **kwargs
  File /home/me/.virtualenvs/proj/local/lib/python2.7/site-packages/fabric/tasks.py, line 409, in execute
    ran_jobs = jobs.run()
  File /home/me/.virtualenvs/proj/local/lib/python2.7/site-packages/fabric/job_queue.py, line 136, in run
    _advance_the_queue()
  File /home/me/.virtualenvs/proj/local/lib/python2.7/site-packages/fabric/job_queue.py, line 121, in _advance_the_queue
    job.start()
  File /usr/lib/python2.7/multiprocessing/process.py, line 130, in start
    self._popen = Popen(self)
  File /usr/lib/python2.7/multiprocessing/forking.py, line 126, in __init__
    code = process_obj._bootstrap()
  File /usr/lib/python2.7/multiprocessing/process.py, line 274, in _bootstrap
    sys.stderr.write('Process %s:' % self.name)
IOError: [Errno 11] Resource temporarily unavailable
```

When I hide some output levels, it runs fine. I have pretty high limits so I doubt it's a case. Also, I have never seen this errors in Ubuntu 12.04. It started showing up when I upgraded to 14.04.

I use Fabric 1.10.2 and Paramiko 1.16.0.

I appreciate any help and suggestions!

**Comment by bitprophet** [comment] 2015-12-01 21:44
Thanks for the report! I'm going to close it as "almost definitely not a bug or anything Fabric itself can change" but that won't close comments - if we can determine an easy cause we can reopen & make the action item "add an FAQ to the docs".

----

Definitely smells like some lower level interaction with the OS, especially given the trigger was OS upgrade and since it's happening in `sys.stderr.write`. I don't recall seeing this before offhand but if you haven't searched the tracker, definitely do so!

It may simply be some sort of concurrency issue with your terminal pipes, too many of the subprocesses (because -P creates multiple actual processes, this isn't threading) writing to your terminal at once when enough stuff is flying around. That's the kind of thing I'd expect to change when the OS, kernel parameters or terminal app or etc, gets upgraded - though again I don't know of specifics.

If possible you could try artificially reproducing it by changing the remote command being executed, to a dummy program that prints a controllable amount of (e.g. lorem ipsum) output (which you can then alter at will to 'bisect' the issue til you narrow down a ballpark figure).

Also try changing the value given to `-P` to see if the problem only starts popping up after some threshold is crossed re: number of processes (and/or combined with amount of output, as above - though I'm guessing it's probably "given an effectively constant output stream from each process, how many processes does it take to trigger this limitation?", meaning you just want the amount of output for each subprocess to be Very Large).

**Closed by bitprophet** 2015-12-01 21:44 UTC

**Comment by Quuxplusone** [comment] 2016-11-30 00:50
"Me too": We see this consistently when running one particular fab (without `-P`, but it executes other fab functions with `parallel=True` and it's one of those subfabs that raises the exception):

```
Fatal error: One or more hosts failed while executing task 'anonymized_foobar'

Underlying exception:
    Resource temporarily unavailable
```

We have a folk-remedy workaround which is to use this `safe_parallel_fab.sh` instead of the `fab` driver:
```
#!/bin/bash
BUF="/tmp/buffer$$"
echo >$BUF
tail -f $BUF &
pid="$!"
trap 'kill $pid && rm $BUF' exit
~/env/bin/python -u `which fab` "$@" >$BUF 2>&1
```

I don't (yet) know why or how it avoids the error.
