### ISSUE TITLE
Update to README.rst

### ISSUE THREAD

**Issue by menollycg** [fabric/fabric#2277] opened 2023-08-18 19:46 UTC
Recommend to update the README.rst file to better explain the purpose of Fabric rather than have the user/contributor have to go to the main website.  Please consider my submission.
[Fabric_README.zip](https://github.com/fabric/fabric/files/12383587/Fabric_README.zip)

**Comment by Theory903** [comment] 2023-12-05 04:30
[README.md](https://github.com/fabric/fabric/files/13555125/README.md)
here is the more suitable version of readme file.

**Comment by davidjmemmett** [comment] 2024-09-28 09:58
I'm not sure what the issue is here so I'm going to close this issue as invalid. Please fill out the issue template when raising an issue in order to make it easier to understand and reproduce your issue.

**Closed by davidjmemmett** 2024-09-28 09:58 UTC
