### ISSUE TITLE
upload_template fails if sudo_user is not None

### ISSUE THREAD

**Issue by benjschiller** [fabric/fabric#1352] opened 2015-07-17 21:31 UTC
upload_template has no option to specify the tmp directory, so the logged in user's home directory is. if the sudo_user does not have privileges to write or remove files from that directory, then process fails. there should be a tmp_directory specified and propagated. or the sudo() command should only cp the file, and then use run() to remove it

**Comment by bitprophet** [comment] 2015-07-20 19:32
This feels like a dupe of #932. Thanks!

**Closed by bitprophet** 2015-07-20 19:32 UTC
