### ISSUE TITLE
paramiko error when attempting to make two connections in one command

### ISSUE THREAD

**Issue by sumdog** [fabric/fabric#1255] opened 2015-01-15 04:00 UTC
I'm trying to write a fabric task that will download some of our packages from our debain repo and put them on out client's server. I'm using the following:

```
@task
def publish_to_client(version):

    home = os.path.expanduser('~')
    keyfile = os.path.join(home, '.ssh', ACT_SFTP_KEY_FILE)

    if not os.path.isfile(keyfile):
        print(red('Please install SFTP key from turing/pview into {}'.format(keyfile)))
    else:
        print(green('Using SFTP Key {}'.format(keyfile)))

        downloads = []
        with lcd('/tmp'):
            for p in ['', '-application', '-doc', '-static']:
                deb = 'act{}_{}_all.deb'.format(p, version)
                with settings(host_string=REPOSITORY_SERVER):
                    downloads = downloads + get(os.path.join('/opt/repositories/misc/dists/moe/act/production/binary-all', deb))
                disconnect_all()
            with settings(host_string=ACT_SFTP_SERVER, user='atlist', key_filename=keyfile):
                for d in downloads:
                    put(d)
                    os.unlink(d)
```

If I make two septate tasks using the same `with setttings()`, I can preform the upload. 
and I get the following error:

```
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 419, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/sumit/pactspace/pact/fabfile.py", line 114, in publish_to_ministry
    put(d)
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 647, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/fabric/operations.py", line 346, in put
    ftp = SFTP(env.host_string)
  File "/usr/lib64/python2.7/site-packages/fabric/sftp.py", line 30, in __init__
    self.ftp = connections[host_string].open_sftp()
  File "/usr/lib64/python2.7/site-packages/paramiko/client.py", line 345, in open_sftp
    return self._transport.open_sftp_client()
  File "/usr/lib64/python2.7/site-packages/paramiko/transport.py", line 719, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/usr/lib64/python2.7/site-packages/paramiko/sftp_client.py", line 110, in from_transport
    chan = t.open_session()
  File "/usr/lib64/python2.7/site-packages/paramiko/transport.py", line 543, in open_session
    return self.open_channel('session')
  File "/usr/lib64/python2.7/site-packages/paramiko/transport.py", line 640, in open_channel
    raise e
paramiko.ssh_exception.SSHException: Invalid packet blocking
```

**Comment by kaaveland** [comment] 2015-12-02 19:35
I can not reproduce this with fabric-1.10.2 / paramiko-1.16.0. Tried the following test-case both as a library and as a fabfile:

```python
from fabric import api
from fabric.contrib.files import get, put
from fabric.network import disconnect_all

@api.task
def move_from_a_to_b():

    with api.lcd('/tmp'):

        with api.settings(host_string='a', user='me'):
            download = get('foo)[0]

        disconnect_all()

        with api.settings(host_string='b', user='me'):
            put(download)

if __name__ == '__main__':
    api.execute(move_from_a_to_b)
```

Also tried without the `disconnect_all()` call to no avail.

@sumdog  -- could you maybe check if this has been fixed in a recent version of fabric? Alternatively, which version where you using when you experienced this issue?

**Comment by kaaveland** [comment] 2015-12-02 19:43
Tried several older pairs of fabric / paramiko, can't reproduce this.

**Closed** 2015-12-06 22:26 UTC
