### ISSUE TITLE
How to make fabric to use host ssh config

### ISSUE THREAD

**Issue by sskumarnd** [fabric/fabric#2109] opened 2020-08-16 02:25 UTC
When using fabric(1), i set "env.use_ssh_config = True" in my fabric.py file and it read my host ~/.ssh/config file and worked to connect to remove hosts.

Now i am trying fabric3 with Python 3.8. Since "env" is gone and "os.environ" done have an option (or i am not aware) to set to read the ~/.ssh/config file, i am unable to use it.

I have tried to add this "Config.load_ssh_config" in my fabric.py file, but still no help.

```
#!/Users/fab3/venv/bin/python
from fabric import Connection, Config
from fabric import task
from paramiko.config import SSHConfig
import sys
import os
import pprint

Config.load_ssh_config
@task
def test(c):
    c.run('hostname')
    print(c.host)
    c.run('uname -a')
```

If anyone got this working, would you please shed some light. Appreciate your help on this. I am using the fabric3 in the virtualenv.

Thank you.

**Comment by dgleba** [comment] 2020-08-16 02:32
I am a novice here but I think fabric3 is a deprecated fork of this repo. There is only fabric 2.5 here.

https://pypi.org/project/Fabric3/ points to https://github.com/mathiasertl/fabric/

**Comment by sskumarnd** [comment] 2020-08-16 02:53
oh, i am using 2.5

(venv) MyMac fab % fab -V  
Fabric 2.5.0
Paramiko 2.7.1
Invoke 1.4.1

I see the following in the documentation... as i didn't learn python fully yet, i am not sure how can i use it. An example will be helpful. Thanks. 

Loading and using ssh_config files
How files are loaded
Fabric uses Paramiko’s SSH config file machinery to load and parse ssh_config-format files (following OpenSSH’s behavior re: which files to load, when possible):

An already-parsed SSHConfig object may be given to Config.__init__ via its ssh_config keyword argument; if this value is given, no files are loaded, even if they exist.

A runtime file path may be specified via configuration itself, as the ssh_config_path key; such a path will be loaded into a new SSHConfig object at the end of Config.__init__ and no other files will be sought out.

It will be filled in by the fab CLI tool if the --ssh-config flag is given.
If no runtime config (object or path) was given to Config.__init__, it will automatically seek out and load ~/.ssh/config and/or /etc/ssh/ssh_config, if they exist (and in that order.)

**Comment by dgleba** [comment] 2020-08-16 03:06
I ask someone else to help out here as I am struggling to learn fabric 2.5 myself. I am of no help. I agree with your requests for full examples that demonstrate how to do example tasks on remote hosts and use sudo on those hosts as well.

**Comment by sskumarnd** [comment] 2020-08-16 03:42
we can do sudo on remote hosts this way

c.sudo("whoami", user='oracle')

**Comment by sskumarnd** [comment] 2020-08-16 04:05
I have tried this way, but getting "TimeoutError: [Errno 60] Operation timed out" :(

 % fab --ssh-config /Users/kumar/.ssh/config -H <remote-host> test

**Comment by tasosalvas** [comment] 2020-08-17 17:47
Hey there,

Just popped it to mention the [upgrading](https://www.fabfile.org/upgrading.html) documentation, although you've probably seen it already. Even after I migrated my stuff to fabric2, I found it to be the simplest page to understand how things work out of all the doc.

In fabric2, `~/.ssh/config` is loaded by default, no action required. Say:

```python
from fabric import task

@task
def testmi(c):
    c.run("hostname --fqdn")
```

```sh
# if this works
% ssh myhost

# then this works too
% fab -H myhost testmi
```

Passing custom ssh config files should work as well. I'm not currently using it anywhere but I remember testing it for vagrant. I'm not sure why the command line option doesn't work for you.

Anyway, I wish I could be more help but I have never sat on a mac, just popped in to give a minimal example that should just work.

**Comment by sskumarnd** [comment] 2020-08-18 05:38
Thank you, Tasos.

Today, i have setup and virtualenv for fabric 1.14 and imported by old fabric code there. There also it was not picking up my host ssh config file.

So when i run fabric from venv, it is not using my host .ssh/config.

Anyone use venv and making it to use host ssh configs? Please let me know.

Thanks

**Comment by tasosalvas** [comment] 2020-08-18 09:54
I use both venv and virtualenv and it works fine

**Comment by sskumarnd** [comment] 2020-08-18 16:35
true, i see now the .ssh/config is not working for me outside of venv as well.

Yes, i can ssh to the host in the terminal (because it uses proxyjump specified in the .ssh/config)

sskumarnd@SenthilMac fabric3 % ssh host1
Last login: Tue Aug 18 16:30:51 2020 from 17.188.68.201
-0-ssakkaravel@host1:~ $ uptime
 16:31:08 up 32 days, 21:20,  4 users,  load average: 0.32, 0.32, 0.37
-0-ssakkaravel@host1:~ $

sskumarnd@SenthilMac fabric3 % fab -V
Fabric 2.5.0
Paramiko 2.7.1
Invoke 1.4.1

sskumarnd@SenthilMac fabric3 % ls
fabfile.py

`sskumarnd@SenthilMac fabric3 % fab -H host1 testmi
Traceback (most recent call last):
  File "/usr/local/bin/fab", line 11, in <module>
    load_entry_point('fabric==2.5.0', 'console_scripts', 'fab')()
  File "/usr/local/Cellar/fabric/2.5.0_4/libexec/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/Cellar/fabric/2.5.0_4/libexec/lib/python3.8/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/Cellar/fabric/2.5.0_4/libexec/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/Cellar/fabric/2.5.0_4/libexec/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/sskumarnd/fabric3/fabfile.py", line 7, in testmi
    c.run("hostname --fqdn")
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/Cellar/fabric/2.5.0_4/libexec/lib/python3.8/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/usr/local/Cellar/fabric/2.5.0_4/libexec/lib/python3.8/site-packages/fabric/connection.py", line 634, in open
    self.client.connect(**kwargs)
  File "/usr/local/Cellar/fabric/2.5.0_4/libexec/lib/python3.8/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/local/Cellar/fabric/2.5.0_4/libexec/lib/python3.8/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
sskumarnd@SenthilMac fabric3 %`

**Comment by tasosalvas** [comment] 2020-08-18 18:05
Your package versions seem fine. Maybe test with a simpler config, i.e. a quick local VM, so you're 100% sure the rest of the setup works as intended.

I'm totally guessing by this point, but maybe `paramiko` doesn't know how to deal with `ProxyJump`. A quick search in its doc showed no results.

If I understand correctly, `ProxyJump` is a convenience shorthand for `ProxyCommand`, which `paramiko` does mention supporting. Maybe rephrasing your config to use that instead would be a way to work around the issue.

If a simpler config does work, maybe closing this issue and starting one on `paramiko` about `ProxyJump` specifically would net you better results. Maybe post your `.ssh/config` (minus private data) too, so someone more familiar with the issue can jump in.

**Comment by sskumarnd** [comment] 2020-08-19 15:57
Hi Tasos,
I have uninstalled everything(python2, python3, fab1, fab2.5, etc) from my macbook and then reinstalled only python3 and fab2.5 and the ssh command is working.
I must have messed up some of the libs and softlinks. 

Thank you a lot for your help.

**Comment by tasosalvas** [comment] 2020-08-19 16:26
Oh! I'm very happy to hear that!
Happy hacking :)

**Closed** 2020-08-21 05:01 UTC

**Comment by fuzzy76** [comment] 2022-04-29 12:37
I'm also seeing this. SSH key authentication with a password encrypted key. Is that it?
