### ISSUE TITLE
shell_env() cannot accept **kwargs

### ISSUE THREAD

**Issue by robbyt** [fabric/fabric#1283] opened 2015-02-25 19:19 UTC
I created a dict of environment variables to be passed to the `shell_env` context manager- my code looks sort of like this:

```python
the_d = {"DO_IT": "yes please"}
with shell_env(**the_d):
  sudo("run.sh")
```

However, I get the following error when I run this code:
```python
  File "/Users/rterhaar/Documents/python/virtualenvs/v_env/pkgfarm-django/fabtasks/deploy/helper.py", line 144, in build_virtualenv
    fab_env['virtualenv_target'], req_file)
  File "/Users/rterhaar/Documents/python/virtualenvs/v_env/lib/python2.7/site-packages/fabric/network.py", line 647, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/Users/rterhaar/Documents/python/virtualenvs/v_env/lib/python2.7/site-packages/fabric/operations.py", line 1107, in sudo
    stderr=stderr, timeout=timeout, shell_escape=shell_escape,
  File "/Users/rterhaar/Documents/python/virtualenvs/v_env/lib/python2.7/site-packages/fabric/operations.py", line 907, in _run_command
    _prefix_commands(_prefix_env_vars(command), 'remote'),
  File "/Users/rterhaar/Documents/python/virtualenvs/v_env/lib/python2.7/site-packages/fabric/operations.py", line 710, in _prefix_env_vars
    for k, v in env_vars.iteritems()
  File "/Users/rterhaar/Documents/python/virtualenvs/v_env/lib/python2.7/site-packages/fabric/operations.py", line 710, in <genexpr>
    for k, v in env_vars.iteritems()
  File "/Users/rterhaar/Documents/python/virtualenvs/v_env/lib/python2.7/site-packages/fabric/operations.py", line 48, in _shell_escape
    string = string.replace(char, '\%s' % char)
AttributeError: 'set' object has no attribute 'replace'
```

When I pass individual args to `shell_env` using the normal boring way, it works fine:
```python
with shell_env(DO_IT="yes please"):
  # this works!
  sudo("run.sh")
```

**Comment by toastdriven** [comment] 2015-04-13 16:33
I tried biting this one off but can't reproduce the error as is. I dropped the code sample into the test suite with the following code:

    def test_shell_env_kwargs():
        kwargs = {"ANOTHER_KEY": "value"}

        with shell_env(**kwargs):
            eq_(env.shell_env['ANOTHER_KEY'], 'value')
            eq_(local('env | grep ANOTHER_KEY'), 'value')

        eq_(env.shell_env, {})

And the tests passed without issue.

However, I looked at your traceback again & the exception is `'set' object has no attribute 'replace'`. The Python `set` literal (added in version 2.7 - https://docs.python.org/2.7/whatsnew/2.7.html#other-language-changes) looks just like a dictionary, except you use commas (`{'a', 'b'}`) instead of colons (`{'a': 'b'}`). That makes it really easy to typo & create the wrong data structure.

A test like:

    def test_shell_env_kwargs():
        kwargs = {"ANOTHER_KEY": {"value", "whatev"}}

        with shell_env(**kwargs):
            eq_(env.shell_env['ANOTHER_KEY'], 'value')
            eq_(local('env | grep ANOTHER_KEY'), 'value')

        eq_(env.shell_env, {})

...produces an identical traceback.

@robbyt Can you go back & verify your original script? Changing it to the following ought to be enough to verify:

    the_d = {"DO_IT": "yes please"}
    print type(the_d)
    print type(the_d['DO_IT'])
    with shell_env(**the_d):
        sudo("run.sh")

**Comment by robbyt** [comment] 2015-04-13 17:12
@toastdriven Thanks for checking this out!

Yes, it's possible that I may have had comma instead of a colon in my dict. I've refactored my code so much that I can't find where I originally ran into this problem.

If there's a test that covers this case, this issue should be closed as invalid. Since it was probably just my mistake and not a Fabric bug.

**Comment by sivy** [comment] 2015-04-13 17:31
I'm going to close this (we're sprinting on Fabric at PyCon) but please re-open if it raises it's head again.

**Closed by sivy** 2015-04-13 17:31 UTC
Labels: Bug, Needs investigation
