### ISSUE TITLE
ThreadingGroup fails public key auth for every connection *except one* if .open() or .sftp() not called on each connection before calling run()

### ISSUE THREAD

**Issue by brenmous** [fabric/fabric#2139] opened 2021-02-08 06:02 UTC
Version 2.50.

I have two functions which operate on the same remote hosts, connecting via the same jump gateway and using the same private key. Both functions call a script on the remote hosts using a ThreadingGroup. The difference is function A also transfers the script using connection.put() before executing the script with ThreadingGroup. Function B just runs the script, assuming it has already been transferred.

Function A has always worked, but function B was failing authentication - I was getting `encountered RSA key, expected OPENSSH key` exceptions for each connection __except for one__ which successfully authenticated and ran the script. There's nothing wrong with the key and I believe this is just Paramiko's poor exception messages.

By introducing each difference between function A and B one at a time I found that it's the absence of the put step that is causing the issue. This put step simply iterates through the hosts and calls `put()` on each of them (this was done because I don't see there's a method for using `put` with groups - edit: I see this has been added in 2.6.0). If I add this step into function B, or even just loop over each host and call `sftp()` or `open()`, then the error goes away and all connections successfully run.

I have no idea why this happens. I had a quick poke around and I saw that ThreadingGroup wraps Connections, and calls `run` on the connections, which should call `open` implicitly on the connections, but without doing it manually, all but one fails.

Code example:
```
# Works
def func_a(jump_ip, hostnames, keyfile, script_local, script_remote, user='user'):
    connect_kwargs={'key_filename': keyfile, 'look_for_keys': False}
    jump = Connection(jump_ip, user=user, connect_kwargs=connect_kwargs)
    for host in hostnames:
        with Connection(host, user=user, gateway=gateway, connect_kwargs=connect_kwargs) as c:
            c.put(script_local, script_remote)
    with ThreadingGroup(*hostnames, user=user, gateway=gateway, connect_kwargs=connect_kwargs) as g:
        g.run(script_remote)

# Doesn't work
def func_b(jump_ip, hostnames, keyfile, script_remote, user='user'):
    connect_kwargs={'key_filename': keyfile, 'look_for_keys': False}
    jump = Connection(jump_ip, user=user, connect_kwargs=connect_kwargs)
    # If you uncomment the below, the function works fine
    #for host in hostnames:
        #with Connection(host, user=user, gateway=jump, connect_kwargs=connect_kwargs) as c:
            #c.open()
    with ThreadingGroup(*hostnames, user=user, gateway=gateway, connect_kwargs=connect_kwargs) as g:
            g.run(script_remote)
```

**Comment by brenmous** [comment] 2021-02-08 07:06
Might be related to #2065, will try that tomorrow and see if it also works.

**Comment by brenmous** [comment] 2021-02-09 00:41
Also I see put/get support for Groups is in 2.6.0, which I'm now on.

**Comment by davidjmemmett** [comment] 2021-02-23 19:00
Closing as duplicate of #2065 - thanks for investigating.

**Closed by davidjmemmett** 2021-02-23 19:00 UTC
