### ISSUE TITLE
Fabric stops on ZSH terminal

### ISSUE THREAD

**Issue by varunagrawal** [fabric/fabric#1676] opened 2017-10-13 03:53 UTC
I am running a simple `usermod` command on multiple server machines in order to grant permissions to users. One of the machines has a zsh shell and the rest have bash shells. When I run the `fab <command>`, the program executes correctly for the bash shell machines but stops on the zsh shell machine. I have to hit Ctrl+C in order to get it to continue.

Previously, when the zsh shell machine had a bash shell, this was not an issue. Any idea what may be the problem?

**Comment by bitprophet** [comment] 2017-10-13 23:22
Sounds a lot like zsh's default sign-in behavior, which throws up an interactive prompt asking if you want it to place a default .zshrc in your home directory (or some such thing.) I'd double check this angle, it should pop up under manual ssh as well for example.

**Comment by varunagrawal** [comment] 2017-10-17 00:23
I checked this out. The ZSH shell is not prompting for anything when I log in manually. This behavior is very weird since I don't see it when I switch back to bash. Any ideas?

**Comment by bitprophet** [comment] 2017-10-18 17:10
I don't have any other specific ideas really; I've used zsh on my remote systems for quite some time and this style of hang only ever comes up when it's the dotfiles issue. Ditto my current employer, who has been using zsh + fabric for a number of years too (before I showed up.) So I'm confident the issue isn't solely "zsh being used", there's got to be something else going on.

I can only offer the usual sanity-check stuff like:

- you're 100% sure it's the same user both manually and via fab?
- turn on 'debug' level output in fabric, which will spit out the real, full command being run (typically, with a shell wrapper) - try running _that_ command when logged in manually, see if behavior's any different
- modify your copy of Fabric to print out debug statements in its main run() loop (https://github.com/fabric/fabric/blob/master/fabric/io.py#L61 iirc) to see if you can tell what's going on when it hangs

Gonna close this as "probably not a bug in fabric itself" (& I'm afraid I don't have a lot more time for detailed troubleshooting) but as always, feel free to continue commenting if you find something we can help fix.

**Closed by bitprophet** 2017-10-18 17:10 UTC
